parameters:
#    kunstmaan_admin.example.class: Kunstmaan\AdminBundle\Example

services:
    kunstmaan_admin.menu_builder:
        class: Kunstmaan\AdminBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@translator", [@kunstmaan_media.media_menu]]

    form.type.transportmethod:
        class: Kunstmaan\AdminBundle\Form\Extension\UserRolesType
        arguments: [%security.role_hierarchy.roles%]
        tags:
            - { name: form.type, alias: userroles }

    kunstmaan_admin.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: kunstmaan_admin.menu_builder
        factory_method: mainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

