KunstmaanKAdminBundle_homepage:
    pattern:  /edit
    defaults: { _controller: KunstmaanKAdminBundle:Default:index }

KunstmaanKAdminBundle_pages:
    pattern:  /edit/pages
    defaults: { _controller: KunstmaanKAdminBundle:Pages:index }

KunstmaanKAdminBundle_pages_edit:
    pattern:  /edit/pages/{entityname}/{id}
    defaults: { _controller: KunstmaanKAdminBundle:Pages:edit }
    requirements:
        _method:  GET|POST
        id: \d+
KunstmaanKAdminBundle_media:
    pattern:  /edit/media
    defaults: { _controller: KunstmaanKAdminBundle:Media:index }
    
KunstmaanKAdminBundle_modules:
    pattern:  /edit/modules
    defaults: { _controller: KunstmaanKAdminBundle:Modules:index }
    
KunstmaanKAdminBundle_settings:
    pattern:  /edit/settings
    defaults: { _controller: KunstmaanKAdminBundle:Settings:index }

KunstmaanKAdminBundle_settings_users:
    pattern:  /edit/settings/users
    defaults: { _controller: KunstmaanKAdminBundle:Settings:users }