KunstmaanKAdminBundle_homepage:
    pattern:  /admin
    defaults: { _controller: KunstmaanKAdminBundle:Default:index }

KunstmaanKAdminBundle_pages:
    pattern:  /admin/pages
    defaults: { _controller: KunstmaanKAdminBundle:Pages:index }

KunstmaanKAdminBundle_pages_edit:
    pattern:  /admin/pages/{entityname}/{id}
    defaults: { _controller: KunstmaanKAdminBundle:Pages:edit }
    requirements:
        _method:  GET|POST
        id: \d+
    
KunstmaanKAdminBundle_modules:
    pattern:  /admin/modules
    defaults: { _controller: KunstmaanKAdminBundle:Modules:index }
    
KunstmaanKAdminBundle_settings:
    pattern:  /admin/settings
    defaults: { _controller: KunstmaanKAdminBundle:Settings:index }

KunstmaanKAdminBundle_settings_users:
    pattern:  /admin/settings/users
    defaults: { _controller: KunstmaanKAdminBundle:Settings:users }
