KunstmaanKAdminBundle_homepage:
    pattern:  /edit
    defaults: { _controller: KunstmaanKAdminBundle:Default:index }

KunstmaanKAdminBundle_pages:
    pattern:  /edit/pages
    defaults: { _controller: KunstmaanKAdminBundle:Pages:index }
    
KunstmaanKAdminBundle_media:
    pattern:  /edit/media
    defaults: { _controller: KunstmaanKAdminBundle:Media:index }

KunstmaanKAdminBundle_media_images:
    pattern:  /edit/media/images
    defaults: { _controller: KunstmaanKAdminBundle:Media:images }

KunstmaanKAdminBundle_media_videos:
    pattern:  /edit/media/videos
    defaults: { _controller: KunstmaanKAdminBundle:Media:videos }

KunstmaanKAdminBundle_media_slides:
    pattern:  /edit/media/slides
    defaults: { _controller: KunstmaanKAdminBundle:Media:slides }

KunstmaanKAdminBundle_media_files:
    pattern:  /edit/media/files
    defaults: { _controller: KunstmaanKAdminBundle:Media:files }
    
KunstmaanKAdminBundle_modules:
    pattern:  /edit/modules
    defaults: { _controller: KunstmaanKAdminBundle:Modules:index }
    
KunstmaanKAdminBundle_settings:
    pattern:  /edit/settings
    defaults: { _controller: KunstmaanKAdminBundle:Settings:index }

KunstmaanKAdminBundle_picture_new:
    pattern:  /edit/media/picture/{gallery_id}
    defaults: { _controller: KunstmaanKAdminBundle:Picture:new }
    requirements:
        _method: GET

KunstmaanKAdminBundle_picture_create:
    pattern:  /edit/media/picture/create/{gallery_id}
    defaults: { _controller: KunstmaanKAdminBundle:Picture:create }
    requirements:
        _method: POST
        id: \d

KunstmaanKAdminBundle_imagegallery_new:
    pattern:  /edit/media/gallery
    defaults: { _controller: KunstmaanKAdminBundle:ImageGallery:new }
    requirements:
        _method:  GET
        id: \d+

KunstmaanKAdminBundle_imagegallery_create:
    pattern:  /edit/media/gallery/create
    defaults: { _controller: KunstmaanKAdminBundle:ImageGallery:create }
    requirements:
        _method: POST
        id: \d

KunstmaanKAdminBundle_imagegallery_show:
    pattern:  /edit/media/gallery/{id}/{slug}
    defaults: { _controller: KunstmaanKAdminBundle:ImageGallery:show }
    requirements:
        _method:  GET
        id: \d+

KunstmaanKAdminBundle_imagegallery_ckeditor:
    pattern:  /edit/media/ckeditor
    defaults: { _controller: KunstmaanKAdminBundle:ImageGallery:ckeditor }
    requirements:
        _method:  GET

KunstmaanKAdminBundle_textpart_new:
    pattern:  /edit/pages/textpart
    defaults: { _controller: KunstmaanKAdminBundle:TextPart:new }
    requirements:
        _method:  GET
        id: \d+

KunstmaanKAdminBundle_textpart_create:
    pattern:  /edit/pages/textpart/create
    defaults: { _controller: KunstmaanKAdminBundle:TextPart:create }
    requirements:
        _method: POST
        id: \d

KunstmaanKAdminBundle_textpart_show:
    pattern:  /edit/pages/textpart/{id}
    defaults: { _controller: KunstmaanKAdminBundle:TextPart:show }
    requirements:
        _method:  GET
        id: \d+