parameters:
#    kunstmaan_k_admin.example.class: Kunstmaan\KAdminBundle\Example

services:
#    kunstmaan_k_admin.example:
#        class: %kunstmaan_k_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
  node.listener:
        class: Kunstmaan\KAdminBundle\Listener\NodeGenerator
        tags:
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
            - { name: doctrine.event_listener, event: postPersist, method: postPersist }
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }


