language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_script: build/before_script

script: build/build_script

notifications:
  email:
    - travis@kunstmaan.be
  irc:
    - "hcs01.kunstmaan.be#travis"
