
KunstmaanDemoBundle:
    resource: "@KunstmaanDemoBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements: 
      _locale: nl|fr|en

KunstmaanPagePartBundle:
    resource: "@KunstmaanPagePartBundle/Resources/config/routing.yml"
    prefix:   /

KunstmaanMediaBundle:
    resource: "@KunstmaanMediaBundle/Resources/config/routing.yml"
    prefix:   /

KunstmaanAdminListBundle:
    resource: "@KunstmaanAdminListBundle/Resources/config/routing.yml"
    prefix:   /

KunstmaanAdminNodeBundle:
    resource: "@KunstmaanAdminNodeBundle/Resources/config/routing.yml"
    prefix:   /

KunstmaanAdminBundle:
    resource: "@KunstmaanAdminBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_imagine:
    resource: .
    type:     imagine
    
KunstmaanAdminBundle_annotations:
    resource: "@KunstmaanAdminBundle/Controller/PagesController.php"
    type:     annotation
    prefix:   /{_locale}/
    requirements: 
      _locale: nl|en|fr
      
KunstmaanViewBundle_searchpage:
    resource: "@KunstmaanViewBundle/Controller/SearchPageController.php"
    type:     annotation
    prefix:   /{_locale}/
    requirements: 
      _locale: nl|en|fr

KunstmaanViewBundle_slug:
    resource: "@KunstmaanViewBundle/Controller/SlugController.php"
    type:     annotation
    prefix:   /{_locale}/
    requirements: 
      _locale: nl|en|fr