 
KunstmaanMediaBundle:
    resource: "@KunstmaanMediaBundle/Resources/config/routing.yml"
    prefix:   /

KunstmaanAdminBundle:
    resource: "@KunstmaanAdminBundle/Resources/config/routing.yml"
    prefix:   /
    
KunstmaanPagePartBundle:
    resource: "@KunstmaanPagePartBundle/Resources/config/routing.yml"
    prefix:   /
    
KunstmaanViewBundle_searchpage:
    resource: "@KunstmaanViewBundle/Controller/SearchPageController.php"
    type:     annotation
    prefix:   /

KunstmaanViewBundle_slug:
    resource: "@KunstmaanViewBundle/Controller/SlugController.php"
    type:     annotation
    prefix:   /
    
KunstmaanDemoBundle_default:
    resource: "@KunstmaanDemoBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /
    
  