parameters:
#    kunstmaan_sandbox_demo.example.class: Kunstmaan\SandboxDemoBundle\Example

services:
#    kunstmaan_sandbox_demo.example:
#        class: %kunstmaan_sandbox_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
