kserver:
    dependencies:
        base: Kunstmaan\kServer\Skeleton\BaseSkeleton
        php: Kunstmaan\kServer\Skeleton\PHPSkeleton
        apache: Kunstmaan\kServer\Skeleton\ApacheSkeleton
        mysql: Kunstmaan\kServer\Skeleton\MySQLSkeleton
    name: kunstmaansandbox
    permissions:
        root:
            path: /
            ownership: '-R kunstmaansandbox.kunstmaansandbox'
            acl:
                - '-R -m user::rwx'
                - '-R -m group::---'
                - '-R -m other::---'
        ssh:
            path: /.ssh
            ownership: '-R kunstmaansandbox.kunstmaansandbox'
            acl:
                - '-R -m user::rwX'
                - '-R -m group::---'
                - '-R -m other::---'
                - '-R -m m::---'
        apache:
            path: /
            ownership: '-R kunstmaansandbox.kunstmaansandbox'
            acl:
                - '-R -m u:www-data:r-X'
    backup:
        excluded: null
    url: kunstmaansandbox.kunstmaan.be
    aliases: {  }
    webdir: web
    mysql:
        host: localhost
        port: 3306
        user: sandbox
        password: mengaige
